# Generated by Django 6.0.2 on 2026-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.CharField(blank=True, max_length=10)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('capa', models.URLField(blank=True)),
                ('tipo', models.CharField(choices=[('quero', 'Quero Ler'), ('lido', 'Lido'), ('comprado', 'Comprado')], max_length=10)),
            ],
        ),
    ]
