# Generated by Django 6.0.2 on 2026-02-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='livros',
            new_name='livro',
        ),
    ]
