# Generated by Django 6.0.2 on 2026-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_livros_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='paginas',
            field=models.IntegerField(default=0),
        ),
    ]
