# Generated by Django 6.0.2 on 2026-02-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livro_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='avaliacao',
            field=models.IntegerField(blank=True, choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], null=True),
        ),
    ]
